# Generated by Django 3.1.3 on 2023-08-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'verbose_name_plural': 'Asignaciones'},
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nota_contrato',
            field=models.TextField(),
        ),
    ]
